ch4856 added CryptoCompare exchange handler
makerdao/oracle-suite pull request #46
Opened 2020-08-12 10:02 UTC by konstantinzolotarev

2020-08-12 11:11 UTC, teghnet requested changes

2020-08-12 11:13 UTC, teghnet requested changes

2020-08-13 08:12 UTC, teghnet approved these changes
I am :ok_hand: with the idea of a separate story/stories for a little cleanup :)

2020-08-13 08:23 UTC, icetan approved these changes
:+1:

2020-08-13 08:34 UTC, MDobak approved these changes

2020-08-13 10:36 UTC, merged